### PR TITLE
Check confirmation value on chat close

### LINKED ISSUE #3: Canceling the termination of a conversation does not work
_From @janrudolph on August 14, 2017 7:27_

A conversation is finished (livechat, request). The user likes to terminate the conversation. But the user realizes that there is an additional question. Therefore the user cancels the termination dialog.

**Issue**
It is not possible to cancel the termination dialog. The conversation is closed when pressing the button "Hilfe beenden".

**Solution**
Terminate conversation when user confirms the popup.

_Copied from original issue: mrsimpson/Rocket.Chat#70_

### PR DESCRIPTION
**Pull request by mrsimpson**
fixes #3

### CODE REVIEW

File: packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js [hunk 1]
```diff
@@ -95,33 +95,26 @@ Template.HelpRequestActions.events({
 			closeOnConfirm: false,
 			roomId: instance.data.roomId
 		}), (inputValue) => {
-			/*if (!inputValue) {
-			 swal.showInputError(t('Please_add_a_comment_to_close_the_room'));
-			 return false;
-			 }
+			//inputValue is false on "cancel" and has a string value of the input if confirmed.
+			if (!(typeof inputValue === 'boolean' && inputValue === false)) {
```
Comment (mrsimpson) [inline packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js]: @ruKurz I could have also validated that there is a String provided for the same result.
However, as an empty String (`""`) is evaluated as false in JS, I opted for the inverse.-
wdyt?

Comment (ruKurz) [reply packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js]: As non JS expert I would say:

```
if (isNotEmptyOrWhitespaceOnly(inputValue)) {
  // close
} else {
  // cancel
}
```

Comment (ruKurz) [reply packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js]: I think there should be three cases handled when closing a conversation:

1. Close and store
2. Close and do not store
3. Do not close / cancel the dialog

As far as I understand the code, now it is possible to 
1. close and store
2. cancel the dialog

@mrsimpson WDYT?

Comment (mrsimpson) [reply packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js]: @ruKurz what's the business value of "Close and do not store"
Would this be an explicit decision by the user?

Comment (ruKurz) [reply packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js]: Yes, I think the "explicit decision" is a benefit. But if you aim to grab as much data with Smarti as possible the "close and do not sore option" would cause the lose of conversational data.

So the trade-off is "user control" vs. "data octopus".

**Comment by mrsimpson** [comment]
@ruKurz Please wait with merging, handling the abort. could be nicer.

File: packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js (hunk 1 above)
Comment (mrsimpson) [reply packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js]: @ruKurz I extracted the check into a separate method. Any objections merging it?

Comment (mrsimpson) [reply packages/assistify-help-request/client/views/tabbar/HelpRequestActions.js]: @ruKurz whether we provide a "close but don't store" is another decision, imho.

**Comment by ruKurz** [comment]
Since this issue addresses a bug fix, a new Issue has been opened to discuss wether "Close and do not store" is a required feature or not and if this is part of RC or Smarti.

https://github.com/assistify/Rocket.Chat/issues/6
