### PR TITLE
auto translate StatusCode exception fix

### LINKED ISSUE #382: Auto Translate StatusCode Exception
System Exception is raised in the `sendMessage` callback whenever **AutoTranslation** failed.

```TypeError: Cannot read property 'statusCode' of undefined
    at targetLanguages.forEach.language (/opt/Rocket.Chat/programs/server/packages/assistify_deepl-translation.js:192:18)
    at Array.forEach (<anonymous>:null:null)
    at DeeplAutoTranslate._sendRequestTranslateMessage (/opt/Rocket.Chat/programs/server/packages/assistify_deepl-translation.js:171:21)
    at Meteor.defer (/opt/Rocket.Chat/programs/server/packages/rocketchat_autotranslate.js:297:37)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
    at packages/meteor.js:502:25
    at runWithEnvironment (packages/meteor.js:1238:24)```

### PR DESCRIPTION
**Pull request by vickyokrm**
closes #382.

### CODE REVIEW

File: packages/assistify-deepl-translation/server/deeplTranslate.js [hunk 1]
```diff
@@ -117,24 +117,24 @@ class DeeplAutoTranslate extends AutoTranslate {
...
+
+				if (result.statusCode === 200 && result.data && result.data.translations && Array.isArray(result.data.translations) && result.data.translations.length > 0) {
+					// store translation only when the source and target language are different.
+					if (result.data.translations.map(translation => translation.detected_source_language).join() !== language) {
+						const txt = result.data.translations.map(translation => translation.text).join('\n');
+						translations[language] = this.deTokenize(Object.assign({}, targetMessage, {msg: txt}));
+					}
+				}
 			} catch (e) {
 				console.log('Error translating message', e);
```
Comment (mrsimpson) [inline packages/assistify-deepl-translation/server/deeplTranslate.js]: This should be done using a global `SystemLogger`
