### PR TITLE
[FIX] #345 - where smarti conversation cache got out of synch

### LINKED ISSUE #345: The knowledge base is not displayed in many topics and requests
As intended, an user helped herself by using the knowledge base. However, after closing the room the knowledge base is not available anymore. Please see screenshot below. 

client = `mc`

trotz_hilfe-raum_nicht_gefunden

### PR DESCRIPTION
**Pull request by ruKurz**
Closes #345

**This PR includes:**

- force re-synch all rooms and messages with smarti when re-synch is triggered via admin UI
- updating the livechat-external-message collection when replacing/creating new convIds in smarti
- reducing redundant code for getting conversations

### CODE REVIEW

File: packages/assistify-ai/server/lib/SmartiAdapter.js [hunk 1]
```diff
@@ -35,34 +36,47 @@ export class SmartiAdapter {
...
+		if (m && m.conversationId) {
+			return m.conversationId;
 		} else {
 			SystemLogger.debug('Smarti - Trying legacy service to retrieve conversation ID...');
-			const conversation = SmartiProxy.propagateToSmarti(verbs.get,
-				`legacy/rocket.chat?channel_id=${ roomId }`, null, (error) => {
-					// 404 is expected if no mapping exists
-					if (error.response.statusCode === 404) {
-						return null;
+			const conversation = RocketChat.RateLimiter.limitFunction(
```
Comment (mrsimpson) [inline packages/assistify-ai/server/lib/SmartiAdapter.js]: Any reason you limited this rate?

File: packages/assistify-ai/server/lib/SmartiAdapter.js [hunk 2]
```diff
@@ -35,34 +36,47 @@ export class SmartiAdapter {
...
+				if (error.response.statusCode === 404) {
+					return null;
+				}
+			});
+
 			if (conversation && conversation.id) {
-				conversationId = conversation.id;
-				const timestamp = message ? message.ts : Date.now();
-				SmartiAdapter._updateMapping(roomId, conversationId, timestamp);
+				let timestamp = conversation.messages &&
```
Comment (mrsimpson) [inline packages/assistify-ai/server/lib/SmartiAdapter.js]: Essentially, this is the actual change, right? Instead of utilizing the timestamp from the message, you take the timestamp from the conversation stored in Smarti. How can they differ? I'd love to read some comment about the "why we do it like that" in the code

File: packages/assistify-ai/server/methods/SmartiReload.js [hunk 3]
```diff
@@ -1,18 +1,19 @@
...
 
 import {SmartiProxy, verbs} from '../SmartiProxy';
+import {SmartiAdapter} from '../lib/SmartiAdapter';
 
 Meteor.methods({
 	triggerFullResync() {
 		SystemLogger.info('Full Smarti resync triggered');
 
-		const query = {$or: [{outOfSync: true}, {outOfSync: {$exists: false}}]};
+		const query = {$or: [{outOfSync: true}, {outOfSync: false}, {outOfSync: {$exists: false}}]};
```
Comment (mrsimpson) [inline packages/assistify-ai/server/methods/SmartiReload.js]: now this includes pretty much anything, doesn't it? a boolean value can be absent or have the values true or false. Why did you introduce this? Should we not - given the method name - just remove the selection criterion?

File: packages/assistify-ai/server/methods/SmartiReload.js [hunk 4]
```diff
@@ -137,7 +140,9 @@ Meteor.methods({
 			conversation.messages.push(newMessage);
 		}
 
-		SmartiProxy.propagateToSmarti(verbs.post, 'conversation', conversation);
+		const response = SmartiProxy.propagateToSmarti(verbs.post, 'conversation', conversation);
+		SystemLogger.debug('Update conversation with id: ', response.id);
+		SmartiAdapter.updateMapping(rid, response.id);
```
Comment (mrsimpson) [inline packages/assistify-ai/server/methods/SmartiReload.js]: I believe this should be done implicitly inside the Smarti adapter. Actually, I would expect we don't use the `SmartiProxy` outside the Smarti Adapter. I obviously oversaw this earlier on.

**Comment by ruKurz** [comment]
I've now finished my work so far.

The current status should ensure that the cache for the Smarti analysis results is updated correctly. The most important concepts (visibility of methods and the distribution of responsibilities) were taken into account. In the admin backend there is now an additional option to perform a complete synchronization with Smarti.

**Comment by ruKurz** [comment]
@mrsimpson Thank you for the valuable comments from the review. It would be great if you could take a look at the current state. The most important changes I've made you'll find within the `SmartiAdapter`.

File: packages/assistify-ai/server/SmartiRouter.js [hunk 5]
```diff
@@ -27,7 +27,8 @@ RocketChat.API.v1.addRoute('smarti.result/:_token', {authRequired: false}, {
 		if (this.urlParams._token && this.urlParams._token === rcWebhookToken) {
 
 			SystemLogger.debug('Smarti - got conversation result:', JSON.stringify(this.bodyParams, null, 2));
-			SmartiAdapter.analysisCompleted(this.bodyParams.channelId, this.bodyParams.conversationId, this.bodyParams.token);
+			SmartiAdapter.analysisCompleted(this.bodyParams.channelId, this.bodyParams.conversationId, Date.now(), this.bodyParams.token);
```
Comment (mrsimpson) [inline packages/assistify-ai/server/SmartiRouter.js]: @ruKurz after y'day's decision to use the timestamp of the smarti conversation for the mapping information, why do we pass `Date.now()` into this method actually?

File: packages/assistify-ai/server/lib/SmartiAdapter.js [hunk 6]
```diff
@@ -233,27 +196,92 @@ export class SmartiAdapter {
...
-	 * @param roomId
-	 * @param smartiConversationId
-	 * @param token
+	 * @param roomId - the analyzed room ID
+	 * @param conversationId - the according Smarti conversation ID
+	 * @param timestamp - the analysis timestamp
+	 * @param token - ???
 	 */
-	static analysisCompleted(roomId, smartiConversationId, token) {
+	static analysisCompleted(roomId, conversationId, timestamp, token) {
```
Comment (mrsimpson) [inline packages/assistify-ai/server/lib/SmartiAdapter.js]: Is it not like that we've always got the conversation at hand once this method is called? Then, we could (and should) get the timestamp via `_getLastConversationAnalyzedTime` and remove the `conversationId` and `timestamp` from the signature.

File: packages/assistify-ai/server/methods/SmartiReload.js [hunk 7]
```diff
@@ -58,35 +64,41 @@ Meteor.methods({
...
-			`legacy/rocket.chat?channel_id=${ rid }`, null, (error) => {
-				// 404 is expected if no mapping exists
-				if (typeof error.response === 'undefined') {
-					return null;
-				}
-				if (error.response.statusCode === 404) {
-					return false;
+
+		conversation = RocketChat.RateLimiter.limitFunction(
+			SmartiProxy.propagateToSmarti, 5, 1000, {
```
Comment (mrsimpson) [inline packages/assistify-ai/server/methods/SmartiReload.js]: We should limit the rate of this method being called - but not the interactions inside this method with Smarti - it would slow-down the sync.

File: packages/assistify-ai/server/methods/SmartiReload.js [hunk 8]
```diff
@@ -110,8 +122,13 @@ Meteor.methods({
 				}
 			};
 		} else {
-			SmartiProxy.propagateToSmarti(verbs.delete,
-				`conversation/${ conversation.id }`, null);
+			RocketChat.RateLimiter.limitFunction(
+				SmartiProxy.propagateToSmarti, 5, 1000, {
```
Comment (mrsimpson) [inline packages/assistify-ai/server/methods/SmartiReload.js]: same here: no limiting of the propagation

File: packages/assistify-ai/server/methods/SmartiReload.js [hunk 9]
```diff
@@ -137,7 +154,16 @@ Meteor.methods({
 			conversation.messages.push(newMessage);
 		}
 
-		SmartiProxy.propagateToSmarti(verbs.post, 'conversation', conversation);
+		const analyzedConversation =  RocketChat.RateLimiter.limitFunction(
+			SmartiProxy.propagateToSmarti, 5, 1000, {
```
Comment (mrsimpson) [inline packages/assistify-ai/server/methods/SmartiReload.js]: and again: limiting

**Comment by mrsimpson** [comment]
P.s.: If you merge `develop` into this PR now, a docker image of the PR will be built automatically - at least once you fixed the linting ;)

**Comment by ruKurz** [comment]
Hi @mrsimpson, I had to notice that @Peym4n took out the asynchronous callbacks when updating to Smarti `0.7.0`. Thought I'd just put it back in. I had to realize that the response body from Smarti, which is sent to the RC Webhook, only contains the analysis results and the `roomId` is not included, so I can't notify the room at all. So if we want to get through the current changes, we have to do the analysis synchronously (has been like this since 17.01.2017 anyway all the time, see revision: 45ded30ccec55d7f9f9f77be93883f6fb633612c85)

File: packages/assistify-ai/server/lib/SmartiAdapter.js [hunk 10]
```diff
@@ -160,55 +116,59 @@ export class SmartiAdapter {
...
-		const conversationId = SmartiAdapter._getConversationId(message.rid, message);
-
+		const conversationId = SmartiAdapter.getConversationId(message.rid);
 		if (conversationId) {
 			SystemLogger.debug(`Conversation ${ conversationId } found for channel ${ message.rid }`);
-
 			SystemLogger.debug(`Deleting message from conversation ${ conversationId } ...`);
-			// add message to conversation
 			SmartiProxy.propagateToSmarti(verbs.delete, `conversation/${ conversationId }/message/${ message._id }`);
+			SmartiAdapter._getAnalysisResult(message.rid, conversationId);
```
Comment (mrsimpson) [inline packages/assistify-ai/server/lib/SmartiAdapter.js]: why's and analysis result retrieved after delete?

File: packages/assistify-ai/server/methods/SmartiReload.js [hunk 11]
```diff
@@ -137,8 +117,17 @@ Meteor.methods({
 			conversation.messages.push(newMessage);
 		}
 
-		SmartiProxy.propagateToSmarti(verbs.post, 'conversation', conversation);
-		SystemLogger.debug('New conversation updated with Smarti');
+		// post the new conversation to Smarti
+		const newSmartiConversation = SmartiProxy.propagateToSmarti(verbs.post, 'conversation', conversation);
+		// get the analysis result
+		const analysisResult = SmartiProxy.propagateToSmarti(verbs.get, `conversation/${ newSmartiConversation.id }/analysis`);
```
Comment (mrsimpson) [inline packages/assistify-ai/server/methods/SmartiReload.js]: When submitting `analysis: true` in the body of the post, the analysis is synchronously returned. Thus, the get can be omitted.

**Comment by ruKurz** [comment]
From my side this PR has an nearly good state.

**Open Issues**
[ ] SmartiAdapter.getConversationId should use the legacy endpoint as fallback (depends on: https://github.com/redlink-gmbh/smarti/issues/259)
[ ] SmartiAdapter.onMessage should heal trigger a resync, when at least one message is outdated
[ ] SmartiAdapter.resync should handle livechat rooms as well
[ ] SmartiAdapter.afterCreateChannel should be triggered by a hook (not by createExpertise, createRequestFromRoom, createEquestFromRoomId)
[ ] Changing the Smarti client (and switching back) within Admin UI should be support by the synchronization
[ ] previously implemented end-to-end tests cases do not work because of Rocket.Chat core changes, make them run again
[ ] Conversation remains that created by resync should be cleaned up within MongoDB, ince Smarti does not support real deletion of conversations (https://github.com/redlink-gmbh/smarti/issues/257),

**Comment by ThomasRoehl** [comment]
Created issues:
https://github.com/assistify/Rocket.Chat/issues/350
https://github.com/assistify/Rocket.Chat/issues/351

**Comment by ruKurz** [comment]
The last commit https://github.com/assistify/Rocket.Chat/pull/346/commits/5644649d86123e0e1dd353eb035042643d37637e fixes https://github.com/assistify/Rocket.Chat/issues/350

**Comment by ruKurz** [comment]
tests in circleCI went well. So is there anything keeping us from merging this PR into `develop`?
@mrsimpson could you please accept the requested changes / finish your review?
