### PR TITLE
Room Name upper case is not supported. 

### LINKED ISSUE #235: Create topic with capital letters not working!
### Description:

When you create a topic with capital letters in the name, the letters get changed to lower-case.

### Steps to Reproduce:

Create a new topic with upper-case letters in the name:

greenshot 2018-02-15 13 40 19

Open the Topic:

greenshot 2018-02-15 13 43 11

### Expected behavior:

Topic name is defined as created

### Actual behavior:

Topic name was converted to lower-case letters only

### PR DESCRIPTION
**Pull request by vickyokrm**
closes #235 : Solves the display name inconsistency 

Uses the 'fname(display name)' property of the room name displayed on the screen.

### CODE REVIEW

**Comment by ThomasRoehl** [comment]
There is a Bug with the username lable in direct messages .
greenshot 2018-02-21 16 27 32
This happens with all users. 
The userlist in adminview looks fine though:
image

**Comment by vickyokrm** [comment]
@ThomasRoehl There is a setting layout->use real name need to set inorder to hide and show the display names. These settings are now check in the assistify packages as well.

**Comment by ThomasRoehl** [comment]
When you create a topic with capital letters and try to create a new topic with the same name it doesn't show an error that the topic already exists, even though it doesn't let you create it again.

**Comment by mrsimpson** [comment]
After the fix, topics wit uppercased special character names can now be created
image

File: packages/assistify-help-request/client/views/creationDialog/AssistifyCreateExpertise.js [hunk 1]
```diff
@@ -199,17 +199,17 @@ Template.AssistifyCreateExpertise.onCreated(function() {
 			Meteor.call('roomDisplayNameExists', name, (error, result) => {
 				if (error) {
 					return;
-				}
-				if (result) {
+				} else {
```
Comment (mrsimpson) [inline packages/assistify-help-request/client/views/creationDialog/AssistifyCreateExpertise.js]: @vickyokrm I prefer this to be explicit `if...else` compared to returning early in order to prevent subsequent execution. And particularly, the earlier `if (result)` is just wrong for booleans ;)
