### PR TITLE
[FIX] Smarti performance by on-demand-analysis

### LINKED ISSUE #551: Solve performance issues by reducing the conversation analysis triggers
# Actual behavior
Currently `onMessageSent`, `onMessageEdited` and `onMessageDeleted` a smarti analysis is triggered. Since we enabled Smarti in all `channels` and `groups` this leads to a high CPU usage (Smarti).

# Expected behavior
Only if a user has opened the knowledge base Smarti analysis should be triggered when sending, editing oder deleting a message

# Solution
1. Check if the Knowledge Base is opened
2. If the Knowledge Base is opened, append the callback-URL
3. If the Knowledge Base is closed, do not append the callback-URL

### PR DESCRIPTION
**Pull request by mrsimpson**
Closes #551 

## What this solves

Up to now, each message lead to an (asynchronous) analysis of the conversation in Smarti. While it was asynchronous for the consuming Rocket.Chat, it was instantly queued on the Smarti-side. 
Having this triggered for all CUD-operations on messages, this created a huge load.

## What is changing

Now, the analysis is only triggered once the widget is opened (the user is interested in Smarti's results), the analysis is being requested.
This leads to a longer delay, but much reduced total load.

## How it's been done

The triggering of the analysis after message sent/updated has been completely removed. Now, only the state of the conversation is propagated (without any further processing).

Only once the Smarti tab is opened, the analysis is being requested and a callback **on the client** is being registered. This callback itself calls a method triggering an analysis server-side - asynchronously, of course.
Once the callback is reached from Smarti, the already existing mechanism to update the widget (propagate the event of the result) is used.

### CODE REVIEW

File: packages/assistify-ai/client/views/app/tabbar/smarti.js [hunk 1]
```diff
@@ -11,15 +11,25 @@ Template.AssistifySmarti.onCreated(function() {
 
 	this.autorun(() => {
 		if (instance.data.rid) {
-			const helpRequest = RocketChat.models.Rooms.findOne(instance.data.rid);
-			instance.helpRequest.set(helpRequest);
+			const room = RocketChat.models.Rooms.findOne(instance.data.rid);
```
Comment (mrsimpson) [inline packages/assistify-ai/client/views/app/tabbar/smarti.js]: This was only a change I made during reading the code (legacy-wording)

File: packages/assistify-ai/client/views/app/tabbar/smarti.js [hunk 2]
```diff
@@ -89,10 +99,6 @@ Template.AssistifySmarti.helpers({
 		const instance = Template.instance();
 		return { roomId: instance.data.rid };
 	},
-	helpRequestByRoom() {
```
Comment (mrsimpson) [inline packages/assistify-ai/client/views/app/tabbar/smarti.js]: removed unused code

**Comment by mrsimpson** [comment]
Fixed an issue with new rooms not being properly submitted. 
Now, all tests ran successfully
<details>
<summary>Smarti integration tests executed locally</summary>
<pre>
Last stop at: tests/end-to-end/temporary_staged_test/00-preparation.js
-------------- 1 try ---------------
+ cp tests/end-to-end/ui_smarti/00-preparation.js tests/end-to-end/temporary_staged_test
+ CHIMP_PATH=tests/end-to-end/temporary_staged_test
+ npm run chimp-path

> Rocket.Chat@0.70.4 chimp-path /Users/oliverjaegle/projects/Rocket.Chat
> chimp tests/chimp-config.js --path=$CHIMP_PATH

(node:83325) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...


  [Smarti Connection]
    [Status]
      health
        ✓ Smarti should be UP
      Info
        ✓ Access Smarti info
    [Smarti Configuration]
      [Client]
        ✓ check if client already exists
        ✓ delete client if exists
clientid 5c0f68cb3b64f30d853bdbd8
        ✓ create new client
        ✓ check if right client was picked
config post /client/5c0f68cb3b64f30d853bdbd8/config
post config { queryBuilder: 
   [ { _class: 'io.redlink.smarti.model.config.ComponentConfiguration',
       name: 'conversationmlt',
       displayName: 'conversationmlt',
       type: 'conversationmlt',
       enabled: true,
       unbound: false,
       pageSize: 3,
       filter: [Array] },
     { _class: 'io.redlink.smarti.model.config.ComponentConfiguration',
       name: 'conversationsearch',
       displayName: 'conversationsearch',
       type: 'conversationsearch',
       enabled: true,
       unbound: false,
       pageSize: 3,
       filter: [Array] } ] }
        ✓ post query-builder
token 82565f56327667120161a819ee224b85c78b2004/JPnWyeXF
        ✓ post access token
authToken 58M5JpQLKBvNocJ4FoCKnC6o6AI7l2agmO-Rxu5YLUo
userId rocketchat.internal.admin.test
        ✓ Login to Rocket.Chat api (152ms)
        ✓ Update access token in Rocket.Chat
        ✓ Rocket.Chat Settings: enable Knowledgebase
        ✓ Rocket.Chat Settings: activate Smarti (78ms)
        ✓ Rocket.Chat Settings: set Smarti client (73ms)
        ✓ Rocket.Chat Settings: set Rocket.Chat Weebhook token
        ✓ Rocket.Chat Settings: set Smarti base url (56ms)
        ✓ Rocket.Chat Settings: set posting type
        ✓ Logout from Rocketchat api (58ms)
    [RC Configuration]
authToken V9ciop31i0K5mhYTd4Pi0Af90MpXwv5nFG7ZSjpVJDk
userId rocketchat.internal.admin.test
      ✓ Login to Rocket.Chat api (151ms)
 testclient
      ✓ Check Assistify_AI_Smarti_Domain
Assistify_AI_Source 0
      ✓ Check Assistify_AI_Source
Assistify_AI_Enabled true
      ✓ Check Assistify_AI_Enabled
Assistify_AI_RocketChat_Webhook_Token key123
      ✓ Check Assistify_AI_RocketChat_Webhook_Token
Assistify_AI_Smarti_Base_URL http://localhost:8080/
      ✓ Check Assistify_AI_Smarti_Base_URL
authToken-o V9ciop31i0K5mhYTd4Pi0Af90MpXwv5nFG7ZSjpVJDk
userId-o rocketchat.internal.admin.test
      ✓ Logout from Rocketchat api


  24 passing (3s)

+ failed=0
+ set +x
-------------- 1 try ---------------
+ cp tests/end-to-end/ui_smarti/01-integration.js tests/end-to-end/temporary_staged_test
+ CHIMP_PATH=tests/end-to-end/temporary_staged_test
+ npm run chimp-path

> Rocket.Chat@0.70.4 chimp-path /Users/oliverjaegle/projects/Rocket.Chat
> chimp tests/chimp-config.js --path=$CHIMP_PATH

(node:83368) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...


  [Smarti Integration]
	User not logged. logging in...
    Message lifecycle
      ✓ create room is successful (3732ms)
check if client exists 5c0f68cb3b64f30d853bdbd8
      ✓ check if client already exists
token 2c393d180c79b1cbef3e7c58fb29e05d8ca9c135/1k96ZXf8
      ✓ post access token
roomId nkMouHnaZXLWMMmmj name smarti-test-topic1-1544513748197
      ✓ shall find the conversation in Smarti (92ms)
finding  /conversation/5c0f68e53b64f30d853bdbdb/message/W6KEbSPuZDFDEv7v9
      ✓ shall find the message in Smarti
WARNING: the "moveTo" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to use the actions command to emulate pointer events.

(You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)
      ✓ shall modify an edited message in Smarti (3239ms)
WARNING: the "moveTo" command will be deprecated soon. If you have further questions, reach out in the WebdriverIO Gitter support channel (https://gitter.im/webdriverio/webdriverio).
Note: This command is not part of the W3C WebDriver spec and won't be supported in future versions of the driver. It is recommended to use the actions command to emulate pointer events.

(You can disable this warning by setting `"deprecationWarnings": false` in your WebdriverIO config)
      ✓ shall delete the message in Smarti (3145ms)
    [Request]
      First request
        ✓ create is successful (4521ms)
      Second request
        ✓ create is successful (4758ms)
        ✓ knowledgebase answer visible (8170ms)
        ✓ post knowledgebase answer (111ms)


  11 passing (42s)

+ failed=0
+ set +x
-------------- 1 try ---------------
+ cp tests/end-to-end/ui_smarti/02-widget.js tests/end-to-end/temporary_staged_test
+ CHIMP_PATH=tests/end-to-end/temporary_staged_test
+ npm run chimp-path

> Rocket.Chat@0.70.4 chimp-path /Users/oliverjaegle/projects/Rocket.Chat
> chimp tests/chimp-config.js --path=$CHIMP_PATH

(node:83500) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...


  [Smarti Widget]
	User not logged. logging in...
    [Request]
      First request
        ✓ create is successful (3618ms)
      Second request
        ✓ create is successful (14403ms)
        ✓ knowledgebase answer is not visible (18177ms)
        ✓ Add missing tag (6354ms)
        ✓ knowledgebase answer is visible now (99ms)


  5 passing (57s)

+ failed=0
+ set +x
-------------- 1 try ---------------
+ cp tests/end-to-end/ui_smarti/03-resync-smarti.js tests/end-to-end/temporary_staged_test
+ CHIMP_PATH=tests/end-to-end/temporary_staged_test
+ npm run chimp-path

> Rocket.Chat@0.70.4 chimp-path /Users/oliverjaegle/projects/Rocket.Chat
> chimp tests/chimp-config.js --path=$CHIMP_PATH

(node:83693) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...


  [Smarti Connection]
    [Status]
      health
        ✓ Smarti should be UP
      Info
        ✓ Access Smarti info
    [Smarti Configuration]
      [Client]
check if client exists 5c0f68cb3b64f30d853bdbd8
        ✓ check if client already exists
client was alread there 5c0f68cb3b64f30d853bdbd8
        ✓ delete client if exists
clientid 5c0f69483b64f30d853bdbe1
        ✓ create new client
        ✓ check if right client was picked
config post /client/5c0f69483b64f30d853bdbe1/config
post config { queryBuilder: 
   [ { _class: 'io.redlink.smarti.model.config.ComponentConfiguration',
       name: 'conversationmlt',
       displayName: 'conversationmlt',
       type: 'conversationmlt',
       enabled: true,
       unbound: false,
       pageSize: 3,
       filter: [Array] },
     { _class: 'io.redlink.smarti.model.config.ComponentConfiguration',
       name: 'conversationsearch',
       displayName: 'conversationsearch',
       type: 'conversationsearch',
       enabled: true,
       unbound: false,
       pageSize: 3,
       filter: [Array] } ] }
        ✓ post query-builder
token e0cb56c23521a228bf2518ec070a23e7185105a5/xQ7JSm14
        ✓ post access token
authToken Mvc7PRVO5ZETM71A1OAqOaLOkLiX5DVggb988GqnVj-
userId rocketchat.internal.admin.test
        ✓ Login to Rocket.Chat api (128ms)
        ✓ Update access token in Rocket.Chat
        ✓ Rocket.Chat Settings: enable Knowledgebase
        ✓ Rocket.Chat Settings: activate Smarti
        ✓ Rocket.Chat Settings: set Smarti client
        ✓ Rocket.Chat Settings: set Rocket.Chat Weebhook token
        ✓ Rocket.Chat Settings: set Smarti base url
        ✓ Rocket.Chat Settings: set posting type (51ms)
        ✓ Logout from Rocketchat api
    [RC Configuration]
authToken jtvsblN7YCV_zzXFI8SW9z4UAkmbCnhx5iUnRXFVubf
userId rocketchat.internal.admin.test
      ✓ Login to Rocket.Chat api (130ms)
 testclient
      ✓ Check Assistify_AI_Smarti_Domain
Assistify_AI_Source 0
      ✓ Check Assistify_AI_Source
Assistify_AI_Enabled true
      ✓ Check Assistify_AI_Enabled
Assistify_AI_RocketChat_Webhook_Token key123
      ✓ Check Assistify_AI_RocketChat_Webhook_Token
Assistify_AI_Smarti_Base_URL http://localhost:8080/
      ✓ Check Assistify_AI_Smarti_Base_URL
authToken-o jtvsblN7YCV_zzXFI8SW9z4UAkmbCnhx5iUnRXFVubf
userId-o rocketchat.internal.admin.test
      ✓ Logout from Rocketchat api

  [Smarti Configuration]
    [Smarti Configuration]
      [Client]
        ✓ check if client already exists
        ✓ delete client if exists
clientid 5c0f69493b64f30d853bdbe4
        ✓ create new client
        ✓ check if right client was picked
token 65895ab477fc2f2e815f2597d779c1231d38a098/T1vCqFB1
        ✓ post access token
    [Rocket-Chat Configuration]
authToken YI_9aVnvEJb1PI6unV7HklSumC3nUyae28h93Uhn6Xs
userId rocketchat.internal.admin.test
      ✓ Login to Rocket.Chat api (117ms)
      ✓ Update access token in Rocket.Chat
      ✓ Rocket.Chat Settings: enable Knowledgebase (67ms)
      ✓ Rocket.Chat Settings: activate Smarti (51ms)
      ✓ Rocket.Chat Settings: set Smarti client
      ✓ Rocket.Chat Settings: set Rocket.Chat Weebhook token
      ✓ Rocket.Chat Settings: set Smarti base url
 syncclient
      ✓ Check Assistify_AI_Smarti_Domain
Assistify_AI_Source 0
      ✓ Check Assistify_AI_Source
Assistify_AI_Enabled true
      ✓ Check Assistify_AI_Enabled
Assistify_AI_RocketChat_Webhook_Token key123
      ✓ Check Assistify_AI_RocketChat_Webhook_Token
Assistify_AI_Smarti_Base_URL http://localhost:8080/
      ✓ Check Assistify_AI_Smarti_Base_URL
authToken-o YI_9aVnvEJb1PI6unV7HklSumC3nUyae28h93Uhn6Xs
userId-o rocketchat.internal.admin.test
      ✓ Logout from Rocketchat api

  [Test Sync]
	User not logged. logging in...
    [Test full Sync]
      Test synced messaging
        - Send synced message in Request
      Test unsynced messaging
authToken SyHd-OwOIRdVVCVdojngk1VuiiqIZGBXfF3StKDl0ii
userId rocketchat.internal.admin.test
        ✓ Make Smarti unavailable (139ms)
        ✓ Send unsynced message in Request (20146ms)
        ✓ Send second unsynced message in Request (6192ms)
        - Send unsynced message in second Request
authToken CzxqYiLI21gwdrmU9YwCASrKmVoURV4YPv49nBGF4oB
userId rocketchat.internal.admin.test
        ✓ Make Smarti available (308ms)
        ✓ Trigger full resync (38396ms)
        ✓ shall find the conversation in Smarti
      [Cleanup Full Sync Test
        ✓ Cleanup all Conversations in Smarti
    [Test auto Sync]
      - Send synced message in Request
      - Make Smarti unavailable
      - Send unsynced message in Request
      - Make Smarti available
      - Send last synced message in Request


  49 passing (1m)
  7 pending

+ failed=0
+ set +x
-------------- 1 try ---------------
+ cp tests/end-to-end/ui_smarti/05-cleanup.js tests/end-to-end/temporary_staged_test
+ CHIMP_PATH=tests/end-to-end/temporary_staged_test
+ npm run chimp-path

> Rocket.Chat@0.70.4 chimp-path /Users/oliverjaegle/projects/Rocket.Chat
> chimp tests/chimp-config.js --path=$CHIMP_PATH

(node:83999) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...


  [Smarti Cleanup]
    ✓ get Client Id
    ✓ delete client


  2 passing (3s)

+ failed=0
+ set +x
</pre>
</details>

**Comment by mrsimpson** [comment]
I can see some strange behavior opening a new room and writing the first message.

**DO NOT MERGE**

**Comment by mrsimpson** [comment]
I can see some strange behaviour opening a new room and writing the first message.

**DO NOT MERGE**
